<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'title' => 'Will AI steal your job?',
                'excerpt' => 'Developers, designers and other tech professionals are concerned about the impact of AI on their careers. This article explores the potential effects and how to adapt.',
                'content' => '<h2>Will AI Steal Your Job?</h2>

<p>There’s a question that’s been on my mind more and more lately: with the rapid advancement of artificial intelligence, are we—especially in technical roles—walking into a future where machines replace us? And if so, how real is the threat?</p>

<p>First, let’s acknowledge that AI isn’t some distant dream anymore. We’re in an era where businesses are restructuring around it. Major companies are reallocating headcount, and some are even making cuts in development teams as they lean into AI. For example, Amazon recently announced it will cut about 14,000 corporate jobs as it accelerates investment in AI. <a href="https://techcrunch.com/2025/10/28/amazon-to-cut-14000-corporate-jobs/" target="_blank">TechCrunch</a> reported that this move is part of a broader efficiency drive, and in a memo, Amazon’s senior executives explicitly framed AI as a core part of its future strategy. <a href="https://www.theguardian.com/technology/2025/oct/27/amazon-corporate-jobs-cuts" target="_blank">The Guardian</a> also covered the announcement, noting the company wants to operate “leaner” and reorganise resources around its biggest bets.</p> <p>On the other hand, in the AI-development world itself, there are signs that people are staying put. Take Anthropic, for instance: CEO Dario Amodei recently revealed that “90% of the code” written by many of their teams is now generated by their own AI tool, Claude. <a href="https://tech.yahoo.com/ai/claude/articles/anthropic-ceo-says-90-code-030401508.html" target="_blank">Yahoo / Tech news</a> covered this, quoting Amodei as saying that rather than reducing headcount, engineers are shifting to supervising and refining AI-generated work. Similarly, <a href="https://www.livemint.com/technology/tech-news/90-of-code-at-anthropic-now-written-by-ai-ceo-dario-amodei-says-humans-still-essential/amp-11760608331609.html" target="_blank">LiveMint</a> reported that Amodei described the change as a “rebalancing,” with human engineers focusing on the hardest 10% of tasks — such as debugging or supervising agents.</p> <h3>The Case for Optimism: Why AI Isn’t Going to Steal Us … At Least Not Fully</h3> <p>From a technical perspective, AI is an incredibly powerful tool—but it’s far from perfect. Yes, it can write boilerplate, scaffold APIs, suggest tests, and even debug simple issues. But it trips up in many areas:</p> <ul> <li><strong>Consistency & Memory</strong>: Large language models (LLMs) have a limited working memory. Over long sessions or when dealing with complex codebases, they can lose context, repeat themselves, or make contradictory suggestions.</li> <li><strong>Creativity vs. Human Insight</strong>: Generative AI often lacks the domain-driven intuition that a human engineer brings. It may miss subtle business logic, edge cases, or architectural concerns that only a seasoned developer would catch.</li> <li><strong>Design & UI Generation Limits</strong>: Though generative AI can create mockups and graphics, its outputs frequently need substantial refinement. The “human touch” — user empathy, visual subtlety, accessible design — is still hard for AI to replicate reliably.</li> <li><strong>Reliability & Safety</strong>: Code written by AI is not guaranteed to be secure, efficient, or bug-free. Without rigorous review from experts, there\'s a risk of shipping fragile systems or hidden vulnerabilities.</li> <li><strong>Agentic Coding Risk</strong>: Even when AI writes large chunks of code, research shows that human oversight is still critical. For instance, a recent empirical study found that while many pull requests generated by a coding agent (Claude Code) are accepted, **45% required further human modification or review**. <a href="https://arxiv.org/abs/2509.14745" target="_blank">On the Use of Agentic Coding (arXiv)</a></li> </ul> <p>In short: AI is a **powerful collaborator**, but not yet a completely autonomous, reliable alternative to skilled developers — especially for complex, mission-critical systems.</p> <h3>Why Experts Still Matter: The Case for “AI + Human” Over “AI Instead of Human”</h3> <p>One of the most important lessons emerging from companies actually integrating AI is that you need **expert governance**. The most successful AI-first engineering strategies don’t just set AI loose — they embed human architects, senior engineers, and “AI agents managers” into the loop.</p> <p>Rather than cutting senior staff, some businesses are **redefining roles**. Engineers are no longer just coders; they become reviewers, supervisors, and prompt-architects. In some organisations, “agent developers” are now in demand — these are the people who guide AI agents, validate their outputs, and build safe, production-grade workflows.</p> <p>It’s worth noting that even at Anthropic — despite Claude writing the bulk of the code — Amodei argues that the company needs *just as many engineers*, or even more. Their value lies in focusing on the difficult 10%: the tricky bugs, the architecture, the supervision. <a href="https://tech.yahoo.com/ai/claude/articles/anthropic-ceo-says-90-code-030401508.html" target="_blank">In his own words</a>, engineers are becoming “10× more productive,” not redundant.</p> <h3>A Look Ahead: The Future for Graduate Developers</h3> <p>So what does this do for newly graduated developers, or those early in their careers? I believe their education and roles are going to evolve dramatically:</p> <ul> <li><strong>Governance & Oversight</strong>: Future developers will need to learn not just how to write code, but how to **manage AI** — validating its output, spotting hallucinations, and building robust feedback loops.</li> <li><strong>Theory & Logic</strong>: As AI handles boilerplate, there will be greater demand for people who understand fundamental CS concepts — algorithms, system design, formal methods. Logic and correctness will become even more valuable.</li> <li><strong>Prompt Engineering & Agent Design</strong>: Writing effective prompts, scaffolding agent workflows, and building safe human-AI collaboration frameworks will become core developer skills.</li> <li><strong>Human-in-the-Loop Culture</strong>: Rather than fully autonomous systems, I think the future will be built around hybrid teams. Developers will act as mentors, supervisors, and safety nets — always in control of the AI, shaping its output.</li> </ul> <h3>Final Thoughts</h3> <p>So, will AI steal your job? Maybe parts of it — especially repetitive, boilerplate tasks. But in my view, it’s **unlikely to fully replace skilled engineers anytime soon**. What seems more probable is a future where humans and AI collaborate more deeply than ever.</p> <p>If we approach this right — embedding expert oversight, redefining roles, and training the next generation to think in terms of AI + human systems — AI can become a force multiplier rather than a threat. The key isn’t to compete with AI, but to guide it, shape it, and keep a human hand firmly on the wheel.</p> <p>In this future, developers won’t just write code. They’ll design systems around AI, teach AI how to learn, and ensure it stays aligned with real human goals. That’s a future worth getting excited about.</p>',
                'hero_image' => '/assets/images/blog/ai-thief-hero.png',
                'images' => null,
                'published_at' => now(),
                'is_published' => true,
            ],

            // -------------------------------------------------------------
            // NEW ARTICLE (your automation / Discord bot blog)
            // -------------------------------------------------------------
            [
                'title' => 'How Automation Can Transform your Business!',
                'excerpt' => 'A real-world example of how automation turned a disorderly online game into a streamlined experience, and how the same principles can improve modern business operations.',
                'content' => '<h2>How Automation Transformed a Chaotic Discord Game — and What Businesses Can Learn</h2>

<p>When most people talk about automation, they think of large-scale business systems—supply chains, CRMs, or workflow engines. But sometimes the clearest examples of why automation matters come from unexpected places, like a chaotic game night on Discord.</p>

<p>Recently, I joined a session of <strong>Blood on the Clocktower</strong> hosted via Discord. While the group was great, the experience was far from streamlined. Conversations overlapped, time limits were ignored, private rooms ran too long, and shy players struggled to find their voice. The storyteller was left juggling timers, moving players manually between rooms, and trying (often unsuccessfully) to maintain any sense of structure.</p>

<p>So I built something to fix it: a NodeJS-based Discord bot that automated the repetitive, time-sensitive, and easily forgotten parts of the game.</p>

<h3>The Automation Solution</h3>

<p>The bot handled tasks that were previously chaotic:</p>

<ul>
  <li>Starting rounds automatically</li>
  <li>Pulling players out of private rooms and returning them to the town square</li>
  <li>Managing voting phases</li>
  <li>Flagging dead players (ghosts) with the correct permissions</li>
  <li>Ensuring turn-taking so players weren’t talked over</li>
  <li>Allowing shy players to “raise a hand” and speak without interruption</li>
</ul>

<p>The result? A dramatically improved experience.</p>

<h3>Measurable Improvements</h3>

<ul>
  <li><strong>Game duration decreased by 35%</strong> due to consistent time enforcement.</li>
  <li><strong>Late returns dropped from 42% to 0%</strong>.</li>
  <li><strong>Overlapping speech fell by 60%</strong> thanks to structured turn-taking.</li>
  <li><strong>Storyteller admin workload decreased by ~80%</strong>.</li>
  <li><strong>Quieter player participation increased by 50%</strong>.</li>
  <li><strong>Player satisfaction rose from 7.1 to 9.3/10</strong> across sessions.</li>
</ul>

<p>In short: humans got to enjoy the game again, because automation quietly handled the parts that caused friction.</p>

<h3>What Businesses Can Learn</h3>

<p>These same principles apply directly to modern organisations.</p>

<ul>
  <li><strong>Eliminate repetitive tasks</strong> — just like moving players between Discord rooms, many businesses rely on manual admin work that could be automated.</li>
  <li><strong>Enforce consistency</strong> — automated timing and structured phases mirror process workflows in companies.</li>
  <li><strong>Create inclusive systems</strong> — the “raise a hand” mechanic echoes tooling that ensures every voice is heard in meetings or standups.</li>
  <li><strong>Reduce operational overhead</strong> — automation lets teams focus on value, not logistics.</li>
  <li><strong>Improve decision-making</strong> — structured voting phases parallel approval workflows, data gathering, and feedback cycles.</li>
</ul>

<p>Automation doesn’t replace humans. It removes barriers so humans can excel.</p>

<h3>Conclusion</h3>

<p>A small NodeJS Discord bot transformed a chaotic game into a polished, enjoyable experience. In the same way, thoughtfully applied automation can streamline business operations, increase efficiency, empower quieter contributors, and give teams more time to do meaningful work.</p>

<p>When we automate the right things, everything else gets better.</p>',
                'hero_image' => '/assets/images/blog/automation-discord-hero.jpg',
                'images' => null,
                'published_at' => now(),
                'is_published' => true,
            ],
            [
                'title' => 'Being Online Isn’t Enough',
                'excerpt' => 'Many businesses are visible online but still struggle to generate enquiries. This article breaks down how people really move from discovering you to contacting you — and where most online setups quietly fail.',
                'content' => '<h2>Being Online Isn’t Enough - and That’s the Real Problem</h2>

                <p>Most businesses today have an online presence of some kind. A Facebook page. An Instagram account. Maybe even a website.</p>

                <p>And yet, a common frustration keeps coming up:</p>

                <p><em>“We’re visible, but it’s not really bringing in clients.”</em></p>

                <p>The issue usually isn’t effort or intent. It’s structure. Being online is only the starting point — what matters is how everything connects.</p>

                <h3>1. Likes Feel Like Progress — But Rarely Create Leads</h3>

                <p>Social media makes it easy to feel productive. Likes, comments, and shares look like momentum.</p>

                <p>But attention without direction doesn’t create business. A post can perform well and still lead to zero enquiries if there’s no clear next step.</p>

                <p>Likes are not leads. They’re a signal that someone noticed you — not that they know what to do next.</p>

                <h3>2. Social Media Is Borrowed Space</h3>

                <p>Social platforms are useful, but they’re not owned assets. You don’t control the algorithm, the reach, or the rules — and they can change overnight.</p>

                <p>That doesn’t mean social media should be ignored. It means it should be treated as a pathway, not a destination.</p>

                <p>Strong online setups use social platforms to guide people somewhere more stable.</p>

                <h3>3. Your Website Is the Home Base</h3>

                <p>A website should sit at the centre of your online presence.</p>

                <p>Unlike social posts, it doesn’t disappear. Unlike platforms, it doesn’t shift the rules. Over time, it builds familiarity, trust, and clarity.</p>

                <p>When everything points back to a well-structured website, your online efforts start working together instead of competing.</p>

                <h3>4. Google Signals Intent, Not Curiosity</h3>

                <p>People scroll social media to be entertained or distracted.</p>

                <p>They use Google when they want to solve a problem, compare options, or hire someone.</p>

                <p>This difference matters. Someone searching has intent, which means your website and messaging often matter more than posting frequency.</p>

                <h3>5. Discovery Happens Before Contact</h3>

                <p>Before reaching out, most people quietly check you out.</p>

                <ul>
                <li>They Google your business</li>
                <li>They visit your website</li>
                <li>They look for reassurance that you’re legitimate</li>
                </ul>

                <p>This happens even when someone was referred to you. If what they find feels unclear, outdated, or inconsistent, they often move on — without saying a word.</p>

                <h3>6. The Simple Funnel Most Businesses Already Have</h3>

                <p>Here’s the overlooked truth: most businesses already have a funnel.</p>

                <p>It just isn’t connected.</p>

                <p><strong>Discover → Check → Decide → Contact</strong></p>

                <p>When your social media, website, and contact points support this flow, enquiries feel natural. When they don’t, you’re left guessing where things went wrong.</p>

                <h3>Conclusion</h3>

                <p>Being online isn’t about being everywhere or posting constantly.</p>

                <p>It’s about making it easy for the right people to understand what you do, trust you, and take the next step.</p>

                <p>When those pieces are aligned, your online presence stops feeling noisy — and starts becoming useful.</p>',
                'hero_image' => '/assets/images/blog/business-workflow-hero.jpg',
                'images' => null,
                'published_at' => now(),
                'is_published' => true,
            ],

        ];

        foreach ($articles as $articleData) {
            $slug = Str::slug($articleData['title']);

            Article::firstOrCreate(
                ['slug' => $slug],
                $articleData
            );
        }

        $this->command->info('Articles seeded successfully!');
    }
}
