<?php

namespace Database\Seeders;

use App\Models\Article;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articles = [
            [
                'title' => 'Will AI steal your job?',
                'excerpt' => 'Developers, designers and other tech professionals are concerned about the impact of AI on their careers. This article explores the potential effects and how to adapt.',
                'content' => '<h2>Will AI Steal Your Job?</h2>

<p>There’s a question that’s been on my mind more and more lately: with the rapid advancement of artificial intelligence, are we—especially in technical roles—walking into a future where machines replace us? And if so, how real is the threat?</p>

<p>First, let’s acknowledge that AI isn’t some distant dream anymore. We’re in an era where businesses are restructuring around it. Major companies are reallocating headcount, and some are even making cuts in development teams as they lean into AI. For example, Amazon recently announced it will cut about 14,000 corporate jobs as it accelerates investment in AI. <a href="https://techcrunch.com/2025/10/28/amazon-to-cut-14000-corporate-jobs/" target="_blank">TechCrunch</a> reported that this move is part of a broader efficiency drive, and in a memo, Amazon’s senior executives explicitly framed AI as a core part of its future strategy. <a href="https://www.theguardian.com/technology/2025/oct/27/amazon-corporate-jobs-cuts" target="_blank">The Guardian</a> also covered the announcement, noting the company wants to operate “leaner” and reorganise resources around its biggest bets.</p>

<p>On the other hand, in the AI-development world itself, there are signs that people are staying put. Take Anthropic, for instance: CEO Dario Amodei recently revealed that “90% of the code” written by many of their teams is now generated by their own AI tool, Claude. <a href="https://tech.yahoo.com/ai/claude/articles/anthropic-ceo-says-90-code-030401508.html" target="_blank">Yahoo / Tech news</a> covered this, quoting Amodei as saying that rather than reducing headcount, engineers are shifting to supervising and refining AI-generated work. Similarly, <a href="https://www.livemint.com/technology/tech-news/90-of-code-at-anthropic-now-written-by-ai-ceo-dario-amodei-says-humans-still-essential/amp-11760608331609.html" target="_blank">LiveMint</a> reported that Amodei described the change as a “rebalancing,” with human engineers focusing on the hardest 10% of tasks — such as debugging or supervising agents.</p>

<h3>The Case for Optimism: Why AI Isn’t Going to Steal Us … At Least Not Fully</h3>

<p>From a technical perspective, AI is an incredibly powerful tool—but it’s far from perfect. Yes, it can write boilerplate, scaffold APIs, suggest tests, and even debug simple issues. But it trips up in many areas:</p>

<ul>
  <li><strong>Consistency & Memory</strong>: Large language models (LLMs) have a limited working memory. Over long sessions or when dealing with complex codebases, they can lose context, repeat themselves, or make contradictory suggestions.</li>  
  <li><strong>Creativity vs. Human Insight</strong>: Generative AI often lacks the domain-driven intuition that a human engineer brings. It may miss subtle business logic, edge cases, or architectural concerns that only a seasoned developer would catch.</li>  
  <li><strong>Design & UI Generation Limits</strong>: Though generative AI can create mockups and graphics, its outputs frequently need substantial refinement. The “human touch” — user empathy, visual subtlety, accessible design — is still hard for AI to replicate reliably.</li>  
  <li><strong>Reliability & Safety</strong>: Code written by AI is not guaranteed to be secure, efficient, or bug-free. Without rigorous review from experts, there\'s a risk of shipping fragile systems or hidden vulnerabilities.</li>  
  <li><strong>Agentic Coding Risk</strong>: Even when AI writes large chunks of code, research shows that human oversight is still critical. For instance, a recent empirical study found that while many pull requests generated by a coding agent (Claude Code) are accepted, **45% required further human modification or review**. <a href="https://arxiv.org/abs/2509.14745" target="_blank">On the Use of Agentic Coding (arXiv)</a></li>  
</ul>

<p>In short: AI is a **powerful collaborator**, but not yet a completely autonomous, reliable alternative to skilled developers — especially for complex, mission-critical systems.</p>

<h3>Why Experts Still Matter: The Case for “AI + Human” Over “AI Instead of Human”</h3>

<p>One of the most important lessons emerging from companies actually integrating AI is that you need **expert governance**. The most successful AI-first engineering strategies don’t just set AI loose — they embed human architects, senior engineers, and “AI agents managers” into the loop.</p>

<p>Rather than cutting senior staff, some businesses are **redefining roles**. Engineers are no longer just coders; they become reviewers, supervisors, and prompt-architects. In some organisations, “agent developers” are now in demand — these are the people who guide AI agents, validate their outputs, and build safe, production-grade workflows.</p>

<p>It’s worth noting that even at Anthropic — despite Claude writing the bulk of the code — Amodei argues that the company needs *just as many engineers*, or even more. Their value lies in focusing on the difficult 10%: the tricky bugs, the architecture, the supervision. <a href="https://tech.yahoo.com/ai/claude/articles/anthropic-ceo-says-90-code-030401508.html" target="_blank">In his own words</a>, engineers are becoming “10× more productive,” not redundant.</p>

<h3>A Look Ahead: The Future for Graduate Developers</h3>

<p>So what does this do for newly graduated developers, or those early in their careers? I believe their education and roles are going to evolve dramatically:</p>

<ul>
  <li><strong>Governance & Oversight</strong>: Future developers will need to learn not just how to write code, but how to **manage AI** — validating its output, spotting hallucinations, and building robust feedback loops.</li>  
  <li><strong>Theory & Logic</strong>: As AI handles boilerplate, there will be greater demand for people who understand fundamental CS concepts — algorithms, system design, formal methods. Logic and correctness will become even more valuable.</li>  
  <li><strong>Prompt Engineering & Agent Design</strong>: Writing effective prompts, scaffolding agent workflows, and building safe human-AI collaboration frameworks will become core developer skills.</li>  
  <li><strong>Human-in-the-Loop Culture</strong>: Rather than fully autonomous systems, I think the future will be built around hybrid teams. Developers will act as mentors, supervisors, and safety nets — always in control of the AI, shaping its output.</li>  
</ul>

<h3>Final Thoughts</h3>

<p>So, will AI steal your job? Maybe parts of it — especially repetitive, boilerplate tasks. But in my view, it’s **unlikely to fully replace skilled engineers anytime soon**. What seems more probable is a future where humans and AI collaborate more deeply than ever.</p>

<p>If we approach this right — embedding expert oversight, redefining roles, and training the next generation to think in terms of AI + human systems — AI can become a force multiplier rather than a threat. The key isn’t to compete with AI, but to guide it, shape it, and keep a human hand firmly on the wheel.</p>

<p>In this future, developers won’t just write code. They’ll design systems around AI, teach AI how to learn, and ensure it stays aligned with real human goals. That’s a future worth getting excited about.</p>',
                'hero_image' => '/assets/images/blog/ai-thief-hero.png',
                'images' => null,
                'published_at' => now(),
                'is_published' => true,
            ],
        ];

        foreach ($articles as $articleData) {
            // Generate slug from title
            $slug = Str::slug($articleData['title']);

            // Use firstOrCreate to avoid duplicates
            Article::firstOrCreate(
                ['slug' => $slug],
                $articleData
            );
        }

        $this->command->info('Articles seeded successfully!');
    }
}
